[package]
name = "spin-sqlite-libsql"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = "0.1.68"
anyhow = "1.0"
# We don't actually use rusqlite itself, but we'd like the same bundled
# libsqlite3-sys as used by spin-sqlite-inproc.
rusqlite = { version = "0.29.0", features = [ "bundled" ] }
spin-sqlite = { path = "../sqlite" }
spin-world = { path = "../world" }
sqlparser = "0.34"
libsql = { git = "https://github.com/tursodatabase/libsql", rev = "8d59b728f5bdf4ee33a65cb02ad174f311a2c94d", features = ["remote"], default-features = false } # ETA for release: early Jan 2024
tokio = { version = "1", features = ["full"] }
