spin_manifest_version = "1"
authors = ["Adam Reese <adam@reese.io>"]
description = ""
name = "tinygo-llm"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "tinygo-llm"
source = "main.wasm"
allowed_http_hosts = []
ai_models = ["llama2-chat", "all-minilm-l6-v2"]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
