[package]
name = "spin-key-value-azure"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
azure_data_cosmos = "0.11.0"
futures = "0.3.28"
serde = { version = "1.0", features = ["derive"] }
spin-key-value = { path = "../key-value" }
spin-core = { path = "../core" }
tokio = "1"
url = "2"
