spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go that performs outbound HTTP requests."
name = "spin-tinygo-outbound-http"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "tinygo-hello"
source = "tinygo-hello/main.wasm"
allowed_http_hosts = [
    "https://random-data-api.fermyon.app",
    "https://postman-echo.com",
]
[component.trigger]
route = "/hello"
[component.build]
workdir = "tinygo-hello"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"

[[component]]
id = "outbound-http-to-same-app"
source = "outbound-http-to-same-app/main.wasm"
allowed_http_hosts = ["self"]
[component.trigger]
route = "/outbound-http-to-same-app"
[component.build]
workdir = "outbound-http-to-same-app"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
